CLFAGS = -g3 -Wall
CC = gcc
all : stdio_study sysio_study
stdio_study : stdio_study.c
	$(CC) $(CLFAGS) stdio_study.c -o stdio_study
sysio_study: system_io_study.c
	$(CC) $(CFALGS) system_io_study.c -o system_io_study
clean:
	rm stdio_study system_io_study
